#!/usr/bin/env bash
# Script that installs Nginx server and redirects /redirect_me
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx start
