#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using while loop
count=1
while [ $count -lt 11 ];
do
if [ $count -eq 9 ];
then
echo "Best School"
echo "Hi"
else
echo "Best School"
fi
((count++))
done
