#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using while loop
count=1
while [ $count -lt 11 ];
do
if [ $count -eq 4 ];
then
echo "bad luck"
elif [ $count -eq 8 ];
then
echo "good luck"
else
echo "Best School"
fi
((count++))
done
